# Helper functions for testing

# .mat to .rdata
mat_to_rdata <- function(s){
  path <- paste('C:/users/computer/desktop/testdaten_Rrobustsp/', s, '.mat', sep="")
  load(path)
  save(eval(parse(text = s)),)
}

# Load test cases generated by matlab
path_test <- function(s){
  return(paste('C:/users/computer/desktop/testdaten_Rrobustsp/', s, '.rdata', sep=""))
}
